# -*- coding: utf-8 -*-
"""2024.9.4-hello world.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z_MLmY0L-Dv7dC6R9bwkzlW_vDXZMt2q
"""

print("Hello World")

print("Hello Python")
i = 1
while i < 6:
    print(i)
    i += 1

import pylab as py

  x_deg = py.arange(-180, 180+1,)
  x_red = py.deg2rad(x_deg)
  y = py.sin(x_red)

  py.plot(x_deg, y)

  py.xlabel('x(deg)')
  py.ylabel('sin(x)')
  py.grid(True)

